#   Nay Oo Kyaw
#   nayookyaw.nok@gmail.com

FROM node:16.17.0 AS base
WORKDIR /frontend
COPY package.json /frontend
RUN rm -rf node_modules
RUN npm config set user 0
RUN npm config set unsafe-perm true
RUN npm install --legacy-peer-deps

# grant access
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . /frontend